# Generated by Django 4.1.4 on 2022-12-15 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0002_alumno_escuela_profesor_delete_familiar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='deporte',
            new_name='taller',
        ),
        migrations.RemoveField(
            model_name='escuela',
            name='nombre',
        ),
    ]
